config/routes.rb
Rails.application.routes.draw do

  # 新規登録時にエラー文が出るとURLが変わらないようにするため
  devise_scope :patient do
    get 'patients/sign_up' => 'public/registrations#new'
    post 'patients/sign_up' => 'public/registrations#create', as: 'patient_registration'
  end

  devise_for :patients, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_for :admins, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions",
    passwords: 'admin/passwords'
  }

  namespace :admin do
    resources :appointments do
      get "appointment_impossible" => "appointments#appointment_impossible"
    end
    resources :employees
    resources :infections
    resources :patients do
      get :search, on: :collection
      get 'appointment_index' => 'patients#appointment_index'
    end
    resources :symptoms
    resources :treatments
    get 'item' => 'homes#item'
    get 'visit_date/:id' => 'appointments#visit_date', as: 'visit_date'
    get "appointment_request_index" => "appointments#request_index"
  end

    # ルートページ
    root to: "public/homes#about"
    get 'admin/top', to: 'admin/homes#top'
    get "public/top", to: "public/homes#top"
    get "appointment_day_index" => "public/appointments#day_index"
    get "about" => "public/homes#about"

  namespace :public do
    resources :appointments, except: :index do
      member do
        get :history
      end
    end

    resources :patients
  end

  # パスワード再設定のメール確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #deviseでルートページの設定する時の書き方
  # devise_scope :admin do
  #   root to: "admin/sessions#new"
  #   get 'top', to: 'admin/homes#top'
  # end

  # scope :public do
  #   resources :appointments

  #   # public/appointments
  # end

  # scope module: :public do
  #   resources :appointments
  #   # appointments
  # end

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  # scope :publics, -> { where.not(status: ["request", "impossible"]) }

  belongs_to :patient
  belongs_to :charge, class_name: 'Employee', foreign_key: :charge_id, optional: true
  belongs_to :subscriber, class_name: 'Employee', foreign_key: :subscriber_id, optional: true

  has_many :appointment_symptoms
  has_many :symptoms, through: :appointment_symptoms
  has_many :appointment_treatments
  has_many :treatments, through: :appointment_treatments

  validates :remark, length: { maximum: 300 }
  validates :symptom_text, length: { maximum: 300 }
  validates :appointment_date, presence: true
  validate :date_before_start, on: :create
  validate :start_finish_check

  enum status: { confirm: 0, cancel: 1, visit: 2, request: 3, impossible: 4 }

  #一日のアポイント件数を表示
  def self.appointments_list(day)
    self.where(appointment_date: Date.parse(day).beginning_of_day...Date.parse(day).end_of_day, status: ["confirm", "visit"])
  end

  def self.appointments_possible?(day, from, to)
    #アポが入っているかどうか、確定と来院済みのものだけ取得
    from = DateTime.parse("#{day} #{from}")
    to = DateTime.parse("#{day} #{to}")
    self.where(appointment_date: from...to, status: ["confirm", "visit"]).exists?
  end

  #日時バリデーション
  def date_before_start
    return if appointment_date.blank?
    errors.add(:appointment_date, "は今日以降のものを選択してください。") if appointment_date < Date.today
  end

  #時間を数字に変換して時間のバリデーション
  def start_finish_check
    return if appointment_date.blank?
    errors.add(:appointment_date, "は10時から18時30分の間で選択してください") if appointment_date.strftime('%H%M').to_i < 1000 || 1830 < appointment_date.strftime('%H%M').to_i
  end
end

app/models/appointment_form.rb
# 勉強用


class AppointmentForm

#   include ActiveModel::Model
#   include ActiveRecord::AttributeAssignment

#   attr_accessor :patient_id, :appointment_date, :visit_date, :remark, :status, :symptom_text, :treatment_id, :symptom_id

#   validates :appointment_date, presence: true
#   validates :treatment_id, presence: true, allow_blank: true
#   validates :symptom_id, presence: true, allow_blank: true
  
#   def self.initialize_by_appointment(appointment)
#     @patient_id = appointment.patient_id
#     @appointment_date = appointment.appointment_date
#     @visit_date = appointment.visit_date
#     @remark = appointment.remark
#     @status = appointment.status
#     @symptom_text = appointment.symptom_text
#   end

#   def save
#     appointment = Appointment.new(
#       patient_id: patient_id,
#       appointment_date: appointment_date,
#       visit_date: visit_date,
#       remark: remark,
#       status: status,
#       symptom_text: symptom_text
#     )
#     appointment.save
#     AppointmentTreatment.create(treatment_id: treatment_id, appointment_id: appointment.id) if treatment_id.present?
#     AppointmentSymptom.create(symptom_id: symptom_id, appointment_id: appointment.id) if symptom_id.present?
#     appointment.id
#   end
end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @appointment = AdminAppointment.new
    @patients = Patient.all
    @patient = Patient.find(params[:patient_id])
  end

  def create
    @appointment = AdminAppointment.new(appointment_params)
    if @appointment.save
       redirect_to admin_appointment_path(@appointment), notice: "予約が完了しました"
    else
       @patient = Patient.find(params[:appointment][:patient_id])
       flash.now[:alert] = "予約が失敗しました"
       render "new"
    end
  end

  def index
    @employees = Employee.all
    @day = params[:day]
    if @day.blank?
      redirect_to admin_appointments_path(day: Date.current.strftime('%Y-%m-%d'))
    end
  end

  def show
    @appointment = AdminAppointment.find(params[:id])
  end

  def edit
    @appointment = AdminAppointment.find(params[:id])
  end

  def update
    @appointment = AdminAppointment.find(params[:id])
    $request_count = Appointment.where(status: "request").length
    if @appointment.update(appointment_update_params)
      # ステータスがcancelになったら来院日削除
      @appointment.update(visit_date: nil) if @appointment.status == 'cancel'
      redirect_to admin_appointment_path(@appointment), notice: "変更が完了しました"
    else
      flash.now[:alert] = "変更が失敗しました"
      render :edit
    end
  end

  #来院ステータスに変更
  def visit_date
    @appointment = AdminAppointment.find(params[:id])
    @appointment.update(
        visit_date: Time.current,
        status: 2
      )
    flash.now[:notice] = "来院しました"
  end

  #リクエストステータス一覧
  def request_index
    @appointments = AdminAppointment.where(status: "request").page(params[:page])
  end

  # def appointment_impossible
  #   @appointment = AdminAppointment.find(params[:appointment_id])
  #   @appointment.update!(
  #       status: 4
  #     )
  #   $request_count = Appointment.where(status: "request").length
  #   redirect_to admin_appointment_path(@appointment.id)
  # end

  private

  def appointment_params
    params.require(:appointment).permit(:patient_id,
      :appointment_date,
      :remark,
      :symptom_text,
      :status,
      :charge_id,
      :subscriber_id,
      :checked,
      { symptom_ids: []},
      { treatment_ids: []},)
  end

  def appointment_update_params
    params.require(:appointment).permit(:patient_id,
      :appointment_date,
      :charge_id,
      :remark,
      :status,
      :symptom_text,
      :visit_date,
      :subscriber_id,
      :checked,
      { symptom_ids: []},
      { treatment_ids: []})
  end
end

app/helpers/admin/appointments_helper.rb
module Admin::AppointmentsHelper
end

app/views/admin/appointments/_index.html.erb
<!--カルテ部分テンプレート-->
<%= link_to admin_appointment_path(appointment.id) do %>
<!--感染症あればカードの色を黄色に表示-->
  <% if appointment.patient.infections.present? %>
    <div class="card-infection mb-3 border">
  <% else %>
    <div class="card mb-3">
  <% end %>
  
    <div class="card-body">
      <h5 class="card-title"><%= appointment.appointment_date.strftime("%H時%M分") %></h5>
      <div class="card-subtitle mb-2">
        <% if appointment.patient.get_age && appointment.patient.full_name.present? %>
          <%= "#{appointment.patient.full_name} / #{appointment.patient.full_name_kana} / (#{appointment.patient.get_age}歳)" %>
        <% elsif appointment.patient.full_name.present? %>
          <%= "#{appointment.patient.full_name} / #{appointment.patient.full_name_kana}" %>
        <% else %>
          <%= "#{appointment.patient.full_name_kana}" %>
        <% end %>
      </div>
      
      <div class="card-text">

        <div class="row">
          <div class="col-4">治療：</div>
          <div class="col-8">
            <% appointment.treatments.each do |treatment| %>
              <span class="badge badge-pill badge-dark mr-1"><%= treatment.name %></span>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-4">症状：</div>
          <div class="col-8">
            <% appointment.symptoms.each do |symptom| %>
              <span class="badge badge-pill badge-secondary mr-1"><%= symptom.name %></span>
            <% end %>
          </div>
        </div>


        <div class="row">
          <div class="col-4">診療状況：</div>
          <div class="col-8">
            <% if appointment.patient.is_visited?(on: appointment.appointment_date) %>
              再診
            <% else %>
              初診
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-4">予約状態：</div>
          <div class="col-8" >
            <%= appointment_status(appointment) %>
          </div>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/appointments/_show.html.erb
<!--showページ来院ボタン非同期-->
<div class="table">
  <div class="row">
    <div class="col-lg-3">
      予約状態
    </div>
    <div class="col-lg-9">
      <% if appointment.status == "cancel" %>
        <%= tag.span appointment.status_i18n, class: "text-danger" %>
      <% elsif appointment.status.nil? %>
        未登録
      <% else %>
        <%= appointment.status_i18n %>
      <% end %>
    </div>
  </div>
</div>

<div class="table">
  <div class="row">
    <div class="col-lg-3">
      来院日時
    </div>
    <div class="col-lg-9">
      <% unless appointment.visit_date.nil? %>
        <%= appointment.visit_date.strftime("%Y年%m月%d日 %H時%M分") %>
      <% else %>
       未来院
      <% end %>
    </div>
  </div>
</div>

<div class="table">
  <div class="row">
    <div class="col-lg-3">
      予約者
    </div>
    <div class="col-lg-9">
      <% if appointment.subscriber.present? %>
        <%= appointment.subscriber.name %>
      <% else %>
        未登録
      <% end %>
    </div>
  </div>
</div>

<div class="text-center">
  <div class="row">
    <div class="col">
      <% if appointment.visit_date.present? || appointment.status != "confirm"  %>
        <%= link_to "予約編集", edit_admin_appointment_path(appointment.id), class: 'btn btn-outline-info col-3' %>
      <% else %>
        <%= link_to "来院", admin_visit_date_path(appointment.id), remote: true, class: 'btn btn-outline-danger col-3', "data-confirm" => "来院しましたか？" %>
        <%= link_to "予約編集", edit_admin_appointment_path(appointment.id), class: 'btn btn-outline-info col-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/appointments/appointment_request.html.erb
<div class='row'>
  <%= render 'layouts/sidebar' %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>予約依頼</h3>

    <div class="table-title">
      <div class="row">
        <div class="col-md-3">
          [予約日時]
        </div>
        <div class="col-md-2">
          [患者ID]
        </div>
        <div class="col-md-2">
          [患者名]
        </div>
        <div class="col-md-3">
          [症状]
        </div>
        <div class="col-md-2">
          [予約状況]
        </div>
      </div>
    </div>

    <% @appointments.each do |appointment| %>
    <div class="table-index">
      <%= link_to admin_appointment_path(appointment.id) do %>
        <div class="row border-bottom d-flex align-items-end" style = "padding-top: 25px;">
          <div class="col-md-3">
            <%= appointment.appointment_date.strftime("%Y年%m月%d日 %H時%M分") %>
          </div>
          <div class="col-md-2">
            <%= appointment.patient.id %>
          </div>
          <div class="col-md-2">
          <% if appointment.patient.full_name.present? %>
            <%= "#{appointment.patient.full_name} / #{appointment.patient.full_name_kana}" %>
          <% else %>
            <%= appointment.patient.full_name_kana %>
          <% end %>
          </div>
          <div class="col-md-3">
          <% if appointment.symptoms.length != 0 %>
            <% appointment.symptoms.each do |symptom| %>
              <%= symptom.name %>
            <% end %>
          <% else %>
           未登録
          <% end %>
          </div>
          <div class="col-md-2">
          <% if appointment_status(appointment).present? %>
            <%= appointment_status(appointment) %>
          <% else %>
            未登録
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
    <!--<div class="d-flex justify-content-center mt-3">-->
    <!--  <%#= paginate @appointments %>-->
    <!--</div>-->
  </div>
</div>

app/views/admin/appointments/edit.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>予約編集</h3>
      <%= render partial: 'layouts/flash' %>
      <%= render 'layouts/error', obj: @appointment %>

      <%= form_with model: @appointment, url: admin_appointment_path do |f| %>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            患者ID
          </div>
          <div class="col-lg-9">
            <%= @appointment.patient.id %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            患者名
          </div>
          <div class="col-lg-9">
            <% if @appointment.patient.full_name.present? %>
              <%= @appointment.patient.full_name %> / <%= @appointment.patient.full_name_kana %>
            <% else %>
              <%= @appointment.patient.full_name_kana %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :appointment_date, "予約日時" %>
          </div>
          <div class="col-lg-9">
            <%= f.datetime_field :appointment_date, placeholder: "必須", class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label "担当者" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_select :charge_id, Employee.where(is_deleted: false), :id, :name, {include_blank: "選択してください（必須）"}, {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label "治療" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_check_boxes(:treatment_ids, Treatment.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class: "custom-control-input") %>
                <%= b.label(class: "custom-control-label") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label "症状" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_check_boxes(:symptom_ids, Symptom.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class: "custom-control-input") %>
                <%= b.label(class: "custom-control-label") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :symptom_text, "その他症状" %>
          </div>
          <div class="col-lg-9">
            <%= f.text_area :symptom_text, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :remark,"備考" %>
          </div>
          <div class="col-lg-9">
            <%= f.text_area :remark, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :status, "予約状態" %>
          </div>
          <div class="col-lg-9">
            <%= f.select :status, Appointment.statuses_i18n.slice(:confirm, :cancel, :request, :impossible).invert, {prompt: ""}, {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :subscriber_id, "予約者" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_select :subscriber_id, Employee.where(is_deleted: false), :id, :name, {include_blank: "選択して下さい（必須）"}, {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="form-group text-center">
        <%= f.submit "保存", class: 'btn btn-outline-info col-3' %>
      </div>
      <% end %>
  </div>
</div>

app/views/admin/appointments/index.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
    <div class='col mt-3'>
      <div class='col-md-9 offset-md-1'>
        <!--当日の予約一覧-->
        <h3><%= @day.to_date.strftime("%m月%d日") %>の予約一覧</h3>
      </div>
   <div class="row">
        <!--担当者毎に予約一覧を表示-->
        <% @employees.each do |employee| %>
        <!--削除されていない従業員を表示-->
          <% if !employee.is_deleted %>
            <div class="col-lg-4 col-md-6 border-right border-bottom">
              <%= employee.name %>
                <% if employee.appointments_list_on_charge(employee.id, @day).present? %>
                  <% employee.appointments_list_on_charge(employee.id, @day).each_with_index do |appointment, index| %>
                    <%= render partial: 'index', locals: {appointment: appointment, index: index, on: @day} %>
                 <% end %>
                <% else %>
                  ：予約はありません
                <% end %>
            </div>
          <% end %>
       <% end %>
     </div>
    </div>
</div>

app/views/admin/appointments/new.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>予約登録</h3>
      <%= render partial: 'layouts/flash' %>
      <%= render 'layouts/error', obj: @appointment %>

      <%= form_with model: @appointment, url: admin_appointments_path do |f| %>
      <%= f.hidden_field :status, value: "confirm" %>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 mini-title">
            <%= f.label :patient_id, "患者ID" %>
          </div>
          <div class="col-lg-9">
            <%= @patient.id %>
            <%= f.hidden_field :patient_id, :value => @patient.id %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :patient_id, "名前" %>
          </div>
          <div class="col-lg-9">
            <% if @patient.full_name.present? %>
              <%= @patient.full_name %> / <%= @patient.full_name_kana %>
            <% else %>
              <%= @patient.full_name_kana %>
            <% end %>
            <%= f.hidden_field :patient_id, :value => @patient.id %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :appointment_date, "予約日時" %>
          </div>
          <div class="col-lg-9">
            <%= f.datetime_field :appointment_date, placeholder: "必須", class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :charge_id, "担当者" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_select :charge_id, Employee.where(is_deleted: false), :id, :name, {include_blank: "選択して下さい（必須）"}, {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :treatment, "治療" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_check_boxes(:treatment_ids, Treatment.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class:"custom-control-input") %>
                <%= b.label(class:"custom-control-label") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :symptom, "症状" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_check_boxes(:symptom_ids, Symptom.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class:"custom-control-input") %>
                <%= b.label(class:"custom-control-label") %>
              </div>
           <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :symptom_text, "その他症状" %>
          </div>
          <div class="col-lg-9">
            <%= f.text_area :symptom_text, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :remark, "備考" %>
          </div>
          <div class="col-lg-9">
            <%= f.text_area :remark, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3 d-flex align-items-center">
            <%= f.label :subscriber_id, "予約者" %>
          </div>
          <div class="col-lg-9">
            <%= f.collection_select :subscriber_id, Employee.where(is_deleted: false), :id, :name, {include_blank: "選択して下さい（必須）"}, {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="form-group text-center">
        <%= f.submit "新規登録", class: 'btn btn-outline-info col-3' %>
      </div>
      <% end %>
  </div>
</div>

app/views/admin/appointments/request_index.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>予約依頼</h3>

    <div class="table-title">
      <div class="row">
        <div class="col-md-3">
          [予約日時]
        </div>
        <div class="col-md-2">
          [患者ID]
        </div>
        <div class="col-md-2">
          [患者名]
        </div>
        <div class="col-md-3">
          [症状]
        </div>
        <div class="col-md-2">
          [予約状況]
        </div>
      </div>
    </div>

    <% @appointments.each do |appointment| %>
    <div class="table-index">
      <%= link_to admin_appointment_path(appointment.id) do %>
        <div class="row border-bottom d-flex align-items-end" style = "padding-top: 25px;">
          <div class="col-md-3">
            <%= appointment.appointment_date.strftime("%Y年%m月%d日 %H時%M分") %>
          </div>
          <div class="col-md-2">
            <%= appointment.patient.id %>
          </div>
          <div class="col-md-2">
          <% if appointment.patient.full_name.present? %>
            <%= "#{appointment.patient.full_name} / #{appointment.patient.full_name_kana}" %>
          <% else %>
            <%= appointment.patient.full_name_kana %>
          <% end %>
          </div>
          <div class="col-md-3">
          <% if appointment.symptoms.length != 0 %>
            <%# symptom_name = "" %>
            <% appointment.symptoms.each do |symptom| %>
              <%# symptom_name += symptom.name %>
              <%= symptom.name %>
            <% end %>
            <!--文字数-->
            <%#= "t".bytesize %>
            <%#= symptom_name.truncate(10) %>
          <% else %>
           未登録
          <% end %>
          </div>
          <div class="col-md-2">
          <% if appointment_status(appointment).present? %>
            <%= appointment_status(appointment) %>
          <% else %>
            未登録
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
    <div class="d-flex justify-content-center mt-3">
      <%= paginate @appointments %>
    </div>
  </div>
</div>

app/views/admin/appointments/show.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>予約詳細</h3>
    <div id="flash-message">
     <%= render partial: 'layouts/flash' %>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          患者ID
        </div>
        <div class="col-lg-9">
          <%= @appointment.patient_id %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          名前
        </div>
        <div class="col-lg-9">
          <%= link_to admin_patient_path(@appointment.patient.id) do %>
            <% if @appointment.patient.full_name.present? %>
              <%= @appointment.patient.full_name %> / <%= @appointment.patient.full_name_kana %>
            <% else %>
              <%= @appointment.patient.full_name_kana %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          予約日時
        </div>
        <div class="col-lg-9">
          <%= @appointment.appointment_date.strftime("%Y年%m月%d日 %H時%M分") %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          担当者
        </div>
        <div class="col-lg-9">
          <% if @appointment.charge.present? %>
            <%= @appointment.charge.name %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          治療
        </div>
        <div class="col-lg-9">
         <% if @appointment.treatments.length != 0 %>
            <% @appointment.treatments.each do |treatment| %>
              <%= treatment.name %>
            <% end %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          症状
        </div>
        <div class="col-lg-9">
          <% if @appointment.symptoms.length != 0 %>
            <% @appointment.symptoms.each do |symptom| %>
              <%= symptom.name %>
            <% end %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          その他症状
        </div>
        <div class="col-lg-9">
        <% if @appointment.symptom_text.present? %>
          <%= @appointment.symptom_text%>
        <% else %>
          未登録
        <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          備考
        </div>
        <div class="col-lg-9">
          <% if @appointment.remark.present? %>
            <%= @appointment.remark %>
          <% else %>
            なし
          <% end %>
        </div>
      </div>
    </div>

    <div id="visit-status">
      <%= render "show", appointment: @appointment %>
    </div>
  </div>
</div>

app/views/admin/appointments/visit_date.js.erb
$('#flash-message').html("<%= j(render 'layouts/flash') %>");
$('#visit-status').html("<%= j(render 'admin/appointments/show',appointment: @appointment) %>");