config/routes.rb
Rails.application.routes.draw do

  # 新規登録時にエラー文が出るとURLが変わらないようにするため
  devise_scope :patient do
    get 'patients/sign_up' => 'public/registrations#new'
    post 'patients/sign_up' => 'public/registrations#create', as: 'patient_registration'
  end

  devise_for :patients, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_for :admins, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions",
    passwords: 'admin/passwords'
  }

  namespace :admin do
    resources :appointments do
      get "appointment_impossible" => "appointments#appointment_impossible"
    end
    resources :employees
    resources :infections
    resources :patients do
      get :search, on: :collection
      get 'appointment_index' => 'patients#appointment_index'
    end
    resources :symptoms
    resources :treatments
    get 'item' => 'homes#item'
    get 'visit_date/:id' => 'appointments#visit_date', as: 'visit_date'
    get "appointment_request_index" => "appointments#request_index"
  end

    # ルートページ
    root to: "public/homes#about"
    get 'admin/top', to: 'admin/homes#top'
    get "public/top", to: "public/homes#top"
    get "appointment_day_index" => "public/appointments#day_index"
    get "about" => "public/homes#about"

  namespace :public do
    resources :appointments, except: :index do
      member do
        get :history
      end
    end

    resources :patients
  end

  # パスワード再設定のメール確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #deviseでルートページの設定する時の書き方
  # devise_scope :admin do
  #   root to: "admin/sessions#new"
  #   get 'top', to: 'admin/homes#top'
  # end

  # scope :public do
  #   resources :appointments

  #   # public/appointments
  # end

  # scope module: :public do
  #   resources :appointments
  #   # appointments
  # end

end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :appointments, foreign_key: :charge_id
  has_many :appointments, foreign_key: :subscriber_id

  validates :name, presence: true, length: { maximum: 20 }

  #employee担当者毎でappointmentのindex表示
  def appointments_list_on_charge(charge_id, day)
    Appointment.where(charge_id: charge_id)
                    .where(appointment_date: Date.parse(day).beginning_of_day...Date.parse(day).end_of_day, status: ["confirm", "cancel", "visit"])
                    .order(appointment_date: "ASC")
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @employee = Employee.new
    @employees = Employee.page(params[:page])
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
       redirect_to admin_employees_path
    else
       @employees = Employee.page(params[:page])
       render :index
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
       redirect_to admin_employees_path
    else
       render :edit
    end
  end

 def destroy
     employee = Employee.find(params[:id])
     employee.update(is_deleted: true)
     redirect_to admin_employees_path
 end

  private

  def employee_params
    params.require(:employee).permit(:name)
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/edit.html.erb
<div class='row'>
 <%= render 'layouts/item_sidebar' %>
  <div class='col-md-9 offset-md-1 mt-3'>
   <h3>スタッフ名編集</h3>
   <%= render 'layouts/error', obj: @employee %>

   <div class="form-group">
    <%= form_with model: @employee, url: admin_employee_path(@employee), method: :patch do |f| %>
     <div class="row d-flex justify-content-center">
      <div class="col-5 mt-2">
       <%= f.label :スタッフ名 %>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="item-index">
       <%= f.submit "変更保存" ,class: "btn btn-outline-info" %>
     <% end %>
      </div>
     </div>
   </div>

   <div class="row mb-3 d-flex justify-content-center">
    <div class="col-md-5">
    </div>
    <div>
     <%= link_to "削除する", admin_employee_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-secondary" %>
    </div>
   </div>

  </div>
</div>

app/views/admin/employees/index.html.erb
<div class='row'>
 <%= render 'layouts/item_sidebar' %>
  <div class='col-md-9 offset-md-1 mt-3'>
   <h3>スタッフ一覧・追加</h3>
   <%= render 'layouts/error', obj: @employee %>

   <div class="form-group">
    <%= form_with model: @employee, url: admin_employees_path, method: :post do |f| %>
     <div class="row d-flex justify-content-center">
      <div class="col-5 mt-2">
       <%= f.label :スタッフ名 %>
       <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="item-index">
       <%= f.submit "新規登録", class: "btn btn-outline-info" %>
      </div>
     </div>
    <% end %>
  </div>

    <% @employees.each do |employee| %>
     <% if !employee.is_deleted %>
     <div class="row mb-3 border-bottom d-flex justify-content-center">
      <div class="col-md-5">
       <%= employee.name %>
      </div>
      <div>
       <%= link_to "編集する", edit_admin_employee_path(employee), class: "btn btn-block btn-outline-secondary" %>
      </div>
     </div>
     <% end %>
    <% end %>
    <div class="d-flex justify-content-center mt-3">
      <%= paginate @employees %>
    </div>
  </div>
</div>