config/routes.rb
Rails.application.routes.draw do

  # 新規登録時にエラー文が出るとURLが変わらないようにするため
  devise_scope :patient do
    get 'patients/sign_up' => 'public/registrations#new'
    post 'patients/sign_up' => 'public/registrations#create', as: 'patient_registration'
  end

  devise_for :patients, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_for :admins, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions",
    passwords: 'admin/passwords'
  }

  namespace :admin do
    resources :appointments do
      get "appointment_impossible" => "appointments#appointment_impossible"
    end
    resources :employees
    resources :infections
    resources :patients do
      get :search, on: :collection
      get 'appointment_index' => 'patients#appointment_index'
    end
    resources :symptoms
    resources :treatments
    get 'item' => 'homes#item'
    get 'visit_date/:id' => 'appointments#visit_date', as: 'visit_date'
    get "appointment_request_index" => "appointments#request_index"
  end

    # ルートページ
    root to: "public/homes#about"
    get 'admin/top', to: 'admin/homes#top'
    get "public/top", to: "public/homes#top"
    get "appointment_day_index" => "public/appointments#day_index"
    get "about" => "public/homes#about"

  namespace :public do
    resources :appointments, except: :index do
      member do
        get :history
      end
    end

    resources :patients
  end

  # パスワード再設定のメール確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #deviseでルートページの設定する時の書き方
  # devise_scope :admin do
  #   root to: "admin/sessions#new"
  #   get 'top', to: 'admin/homes#top'
  # end

  # scope :public do
  #   resources :appointments

  #   # public/appointments
  # end

  # scope module: :public do
  #   resources :appointments
  #   # appointments
  # end

end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:telephone_number]

  has_many :appointments
  has_many :patient_infections
  has_many :infections, through: :patient_infections

  validates :password, presence: true, on: :create
  validates :last_name, length: { maximum: 20 }
  validates :first_name, length: { maximum: 20 }
  validates :last_name_kana, presence: true, length: { maximum: 20 },
  format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力してください'}
  validates :first_name_kana, presence: true, length: { maximum: 20 },
  format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力してください'}
  validates :patient_text, length: { maximum: 300 }
  validates :telephone_number, numericality: true, uniqueness: true, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }, allow_blank: true
  validate :date_after_start

  # 複数valitatesをまとめたい場合はwith_optionsを使用、バリデーションを分けている
  with_options unless: -> { validation_context == :admin } do #adminが引数に渡された時
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :postal_code, numericality: true, presence: true
    validates :email, presence: true
    validates :birthday, presence: true
    validates :gender, presence: true
    validates :address, presence: true
  end

  enum gender: { man: 0, woman: 1, other: 2 }

  # 初診再診の表示
  def is_visited?(on: Date.today)
    appointments.where("appointment_date < ?", on).where(status: :visit).exists?
  end

  # バリデーション
  def get_age
    return if birthday.nil?
    date_format = "%Y%m%d"
    (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10000
  end

  # 検索機能
  def self.search(keyword)
    where([
      "id = ? OR first_name_kana LIKE ? OR last_name_kana LIKE ?",
      "#{keyword}", "%#{keyword}%", "%#{keyword}%"
      ])
  end

  #フルネーム定義
  def full_name
    "#{self.last_name} #{self.first_name}"
  end

  #フルネームカナ定義
  def full_name_kana
    "#{self.last_name_kana} #{self.first_name_kana}"
  end

  # 誕生日今日以降は選択できないバリデーション
  def date_after_start
      return if birthday.blank?
      errors.add(:birthday, "は今日以前のものを選択してください") if birthday > Date.today
  end

  # 予約依頼チェックしていないものの件数
  def unchecked_appointments
    appointments.where(status: [:confirm, :impossible], checked: false)
  end
end

app/controllers/admin/patients_controller.rb
class Admin::PatientsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save(context: :admin)
      redirect_to admin_patient_path(@patient.id), notice: "登録が完了しました"
    else
      flash.now[:alert] = "登録が失敗しました"
      render "new"
    end
  end

  def index
    @patients = Patient.page(params[:page])
  end

  def search
      @patients = Patient.search(params[:keyword]).page(params[:page])
      @keyword = params[:keyword]
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.attributes = patient_params

    if @patient.save(context: :admin)
       redirect_to admin_patient_path(@patient), notice: "変更が完了しました"
    else
      flash.now[:alert] = "変更が失敗しました"
       render :edit
    end
  end

  #個人予約履歴
  def appointment_index
    @patient = Patient.find(params[:patient_id])
    @appointments = @patient.appointments.page(params[:page]).order(created_at: :desc)
  end

  private

  def patient_params
    params.require(:patient).permit(:last_name,
    :first_name,
    :last_name_kana,
    :first_name_kana,
    :birthday,
    :gender,
    :email,
    :postal_code,
    :address,
    :telephone_number,
    :password,
    { infection_ids: []})
  end
end

app/helpers/admin/patients_helper.rb
module Admin::PatientsHelper
end

app/views/admin/patients/appointment_index.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>
      <% if @patient.full_name.present? %>
        <%= @patient.full_name %>さんの予約履歴
      <% else %>
        <%= @patient.full_name_kana %>さんの予約履歴
      <% end %>
    </h3>

    <div class="table-title">
      <div class="row">
        <div class="col-md-3">
          [予約日時]
        </div>
        <div class="col-md-2">
          [来院日]
        </div>
        <div class="col-md-2">
          [担当者]
        </div>
        <div class="col-md-3">
          [治療]
        </div>
        <div class="col-md-2">
          [予約状況]
        </div>
      </div>
    </div>

    <% @appointments.each do |appointment| %>
    <div class="table-index">
      <%= link_to admin_appointment_path(appointment.id) do %>
        <div class="row border-bottom d-flex align-items-end" style = "padding-top: 25px;">
          <div class="col-md-3">
              <%= appointment.appointment_date.strftime("%Y年%m月%d日 %H時%M分") %>
          </div>
          
          <div class="col-md-2">
            <% if appointment.visit_date.present? %>
              <%= appointment.visit_date.strftime("%Y年%m月%d日") %>
            <% else %>
              未来院
            <% end %>
          </div>
          
          <div class="col-md-2">
            <% if appointment.charge.present? %>
              <%= appointment.charge.name %>
            <% else %>
              未登録
            <% end %>
          </div>
          
          <div class="col-md-3">
            <% if appointment.treatments.length != 0 %>
              <% appointment.treatments.each do |treatment| %>
                <%= treatment.name %>
              <% end %>
            <% else %>
             未登録
            <% end %>
          </div>
          
          <div class="col-md-2">
            <% if appointment.status.present? %>
              <%= appointment.status_i18n %>
            <% else %>
              未登録
            <% end %>
          </div>
          
        </div>
      <% end %>
    </div>
    <% end %>
    <div class="d-flex justify-content-center mt-3">
      <%= paginate @appointments %>
    </div>
  </div>
</div>

app/views/admin/patients/edit.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>患者編集</h3>
      <%= render partial: 'layouts/flash' %>
      <%= render 'layouts/error', obj: @patient %>

      <%= form_with model: @patient, url: admin_patient_path(@patient) do |f| %>

      <div class='form-group'>
        <div class='row'>
          <div class='col-lg-3'>
            <%= f.label :full_name,"名前" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :last_name, "(姓)" %>
            <%= f.text_field :last_name, placeholder: "令和", class: "form-control" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :first_name, "(名)" %>
            <%= f.text_field :first_name, placeholder: "道子", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class='form-group'>
        <div class='row'>
          <div class='col-lg-3'>
            <%= f.label :full_name_kana,"フリガナ" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :last_name_kana, "(セイ)" %>
            <%= f.text_field :last_name_kana, placeholder: "レイワ（必須）", class: "form-control" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :first_name_kana, "(メイ)" %>
            <%= f.text_field :first_name_kana, placeholder: "ミチコ（必須）", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :birthday, "誕生日" %>
          </div>
          <div class="col-lg-8">
            <%= f.date_field :birthday, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :gender, "性別" %>
          </div>
          <div class="col-lg-8">
            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(0), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:man], for: 'patient_gender_man', class: 'custom-control-label' %>
            </div>

            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(1), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:woman], for: 'patient_gender_woman', class: 'custom-control-label' %>
            </div>

            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(2), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:other], for: 'patient_gender_other', class: 'custom-control-label' %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :telephone_number,"電話番号(ハイフンなし)" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :telephone_number, placeholder: "0000000000（必須）", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :email,"メールアドレス" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :email, placeholder: "sample@example.com", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :postal_code,"郵便番号(ハイフンなし)" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :postal_code, placeholder: "0000000", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :address, "住所" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0－0", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :patient_text, "患者注意事項" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_area :patient_text, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :infection_id, "感染症" %>
          </div>
          <div class="col-lg-8">
            <%= f.collection_check_boxes(:infection_ids, Infection.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class: "custom-control-input") %>
                <%= b.label(class: "custom-control-label") %>
              </div>
          <% end %>
          </div>
        </div>
      </div>

      <div class="form-group text-center">
        <%= f.submit "変更を保存", class: 'btn btn-outline-info col-3' %>
      </div>
      <% end %>
  </div>
</div>

app/views/admin/patients/index.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>患者一覧</h3>

    <div class="table-title">
      <div class="row">
        <div class="col-md-2">
          [患者ID]
        </div>
        <div class="col-md-4">
          [名前]
        </div>
        <div class="col-md-2">
          [電話番号]
        </div>
        <div class="col-md-2">
          [性別]
        </div>
        <div class="col-md-2">
          [年齢]
        </div>
      </div>
    </div>

    <% @patients.each do |patient| %>
    <div class="table-index">
      <%= link_to admin_patient_path(patient) do %>
        <div class="row border-bottom d-flex align-items-end" style="padding-top: 25px;">

          <div class="col-md-2">
            <%= patient.id %>
          </div>
          <div class="col-md-4">
            <% if patient.full_name.present? %>
              <%= "#{patient.full_name} / #{patient.full_name_kana}" %>
            <% else %>
              <%= patient.full_name_kana %>
            <% end %>
          </div>
          <div class="col-md-2">
            <% if patient.telephone_number.present? %>
              <%= patient.telephone_number %>
            <% else %>
              未登録
            <% end %>
          </div>
          <div class="col-md-2">
            <% if patient.gender.present? %>
              <%= patient.gender_i18n %>
            <% else %>
              未登録
            <% end %>
          </div>
          <div class="col-md-2">
            <% if patient.get_age.present? %>
              <%= patient.get_age %>歳
            <% else %>
              未登録
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
    <div class="d-flex justify-content-center mt-3">
      <%= paginate @patients %>
    </div>
  </div>
</div>

app/views/admin/patients/new.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>患者登録</h3>
      <%= render partial: 'layouts/flash' %>
      <%= render 'layouts/error', obj: @patient %>

      <%= form_with model: @patient, url: admin_patients_path do |f| %>

      <div class='form-group'>
        <div class='row'>
          <div class='col-lg-3'>
            <%= f.label :full_name,"名前" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :last_name, "(姓)" %>
            <%= f.text_field :last_name, placeholder: "令和", class: "form-control" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :first_name, "(名)" %>
            <%= f.text_field :first_name, placeholder: "道子", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class='form-group'>
        <div class='row'>
          <div class='col-lg-3'>
            <%= f.label :full_name_kana,"フリガナ" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :last_name_kana, "(セイ)" %>
            <%= f.text_field :last_name_kana, placeholder: "レイワ（必須）", class: "form-control" %>
          </div>
          <div class='col-lg-4'>
            <%= f.label :first_name_kana, "(メイ)" %>
            <%= f.text_field :first_name_kana, placeholder: "ミチコ（必須）", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :birthday, "誕生日" %>
          </div>
          <div class="col-lg-8">
            <%= f.date_field :birthday, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :gender, "性別" %>
          </div>
          <div class="col-lg-8">
            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(0), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:man], for: 'patient_gender_man', class: 'custom-control-label' %>
            </div>

            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(1), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:woman], for: 'patient_gender_woman', class: 'custom-control-label' %>
            </div>

            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :gender,Patient.genders.key(2), class: 'custom-control-input' %>
              <%= f.label :gender,Patient.genders_i18n[:other], for: 'patient_gender_other', class: 'custom-control-label' %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :password, "パスワード" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :password, placeholder: "（必須）", required: true, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :telephone_number,"電話番号(ハイフンなし)" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :telephone_number, placeholder: "0000000000（必須）", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :email,"メールアドレス" %>
          </div>
          <div class="col-lg-8">
            <%= f.email_field :email, placeholder: "sample@example.com", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :postal_code,"郵便番号(ハイフンなし)" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :postal_code, placeholder: "0000000", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :address, "住所" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0－0", class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :patient_text, "患者注意事項" %>
          </div>
          <div class="col-lg-8">
            <%= f.text_area :patient_text, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-lg-3">
            <%= f.label :infection_id, "感染症" %>
          </div>
          <div class="col-lg-8">
            <%= f.collection_check_boxes(:infection_ids, Infection.where(is_deleted: false), :id, :name) do |b| %>
              <div class="custom-control custom-checkbox custom-control-inline">
                <%= b.check_box(class: "custom-control-input") %>
                <%= b.label(class: "custom-control-label") %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group text-center">
        <%= f.submit "新規登録", class: 'btn btn-outline-info col-3' %>
      </div>
      <% end %>
  </div>
</div>

app/views/admin/patients/search.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>

    <div class="search-index">
      <h3>【<%= @keyword %>】の検索結果</h3>

      <div class="table-title">
        <div class="row">
          <div class="col-md-2">
            [患者ID]
          </div>
          <div class="col-md-4">
            [名前]
          </div>
          <div class="col-md-2">
            [電話番号]
          </div>
          <div class="col-md-2">
            [性別]
          </div>
          <div class="col-md-2">
            [年齢]
          </div>
        </div>
      </div>

      <% if @patients.any? %>
        <% @patients.each do |patient| %>
        <div class="table-index">
          <%= link_to admin_patient_path(patient) do %>
          <div class="row border-bottom d-flex align-items-end" style = "padding-top: 25px;">
            <div class="col-md-2">
             <%= patient.id %>
            </div>
            
            <div class="col-md-4">
              <% if patient.full_name.present? %>
                <%= "#{patient.full_name} / #{patient.full_name_kana}" %>
              <% else %>
                <%= patient.full_name_kana %>
              <% end %>
            </div>
            
            <div class="col-md-2">
              <% if patient.telephone_number.present? %>
                <%= patient.telephone_number %>
              <% else %>
                未登録
              <% end %>
            </div>
            
            <div class="col-md-2">
              <% if patient.gender.present? %>
                <%= patient.gender_i18n %>
              <% else %>
                未登録
              <% end %>
            </div>
            
            <div class="col-md-2">
              <% if patient.get_age.present? %>
                <%= patient.get_age %>歳
              <% else %>
                未登録
              <% end %>
            </div>
            
          </div>
          <% end %>
        </div>
        <% end %>
        <div class="d-flex justify-content-center mt-3">
          <%= paginate @patients %>
        </div>
      <% else %>
          存在しません。
      <% end %>
    </div>
  </div>
</div>

app/views/admin/patients/show.html.erb
<div class='row'>
  <%= render 'layouts/sidebar', request_count: @request_count %>
  <div class='col-md-9 offset-md-1 mt-3'>
    <h3>患者詳細</h3>
    <%= render partial: 'layouts/flash' %>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          患者ID
        </div>
        <div class="col-lg-9">
          <%= @patient.id %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          名前
        </div>
        <div class="col-lg-9">
          <% if @patient.full_name.present? %>
            <%= @patient.full_name %> / <%= @patient.full_name_kana %>
          <% else %>
            <%= @patient.full_name_kana %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          誕生日
        </div>
        <div class="col-lg-9">
          <% if @patient.birthday.present? %>
            <%= @patient.birthday.strftime("%m月%d日") %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          年齢
        </div>
        <div class="col-lg-9">
          <% if @patient.get_age.present? %>
            <%= @patient.get_age %>歳
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          性別
        </div>
        <div class="col-lg-9">
          <% if @patient.gender.present? %>
            <%= @patient.gender_i18n %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          電話番号
        </div>
        <div class="col-lg-9">
          <% if @patient.telephone_number.present? %>
            <%= @patient.telephone_number %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          メールアドレス
        </div>
        <div class="col-lg-9">
          <% if @patient.email.present? %>
            <%= @patient.email %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          郵便番号
        </div>
        <div class="col-lg-9">
          <% if @patient.postal_code.present? %>
            <%= @patient.postal_code %>
          <% else %>
            未登録
          <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          住所
        </div>
        <div class="col-lg-9">
        <% if @patient.address.present? %>
          <%= @patient.address %>
        <% else %>
          未登録
        <% end %>
        </div>
      </div>
    </div>

    <div class="table">
      <div class="row">
        <div class="col-lg-3">
          感染症
        </div>
        <div class="col-lg-9">
          <% if @patient.infections.length != 0 %>
            <% @patient.infections.each do |infection| %>
              <%=  infection.name %>
            <% end %>
          <% else %>
              なし
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group text-center">
      <%= link_to "予約取得", new_admin_appointment_path(patient_id: @patient), class: 'btn btn btn-outline-danger col-3' %>
      <%= link_to "患者情報編集", edit_admin_patient_path(params[:id]), class: 'btn btn-outline-info col-2' %>
      <%= link_to "予約履歴", admin_patient_appointment_index_path(patient_id: @patient), class: 'btn btn-outline-info col-2'%>
    </div>
  </div>
</div>