config/routes.rb
Rails.application.routes.draw do

  # 新規登録時にエラー文が出るとURLが変わらないようにするため
  devise_scope :patient do
    get 'patients/sign_up' => 'public/registrations#new'
    post 'patients/sign_up' => 'public/registrations#create', as: 'patient_registration'
  end

  devise_for :patients, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_for :admins, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions",
    passwords: 'admin/passwords'
  }

  namespace :admin do
    resources :appointments do
      get "appointment_impossible" => "appointments#appointment_impossible"
    end
    resources :employees
    resources :infections
    resources :patients do
      get :search, on: :collection
      get 'appointment_index' => 'patients#appointment_index'
    end
    resources :symptoms
    resources :treatments
    get 'item' => 'homes#item'
    get 'visit_date/:id' => 'appointments#visit_date', as: 'visit_date'
    get "appointment_request_index" => "appointments#request_index"
  end

    # ルートページ
    root to: "public/homes#about"
    get 'admin/top', to: 'admin/homes#top'
    get "public/top", to: "public/homes#top"
    get "appointment_day_index" => "public/appointments#day_index"
    get "about" => "public/homes#about"

  namespace :public do
    resources :appointments, except: :index do
      member do
        get :history
      end
    end

    resources :patients
  end

  # パスワード再設定のメール確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #deviseでルートページの設定する時の書き方
  # devise_scope :admin do
  #   root to: "admin/sessions#new"
  #   get 'top', to: 'admin/homes#top'
  # end

  # scope :public do
  #   resources :appointments

  #   # public/appointments
  # end

  # scope module: :public do
  #   resources :appointments
  #   # appointments
  # end

end

app/views/layouts/_default_header.html.erb
<!--未ログインのヘッダー、ルートページに遷移-->
<nav class="navbar navbar-light px-0" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= image_tag 'dentalapo2.png', :size => '140x30' %></a>
  </div>
</nav>

app/views/layouts/_error.html.erb
<!--四角で囲まれたエラーメッセージ-->
<% if obj.errors.any? %>
  <div id="error_explanation" class="alert alert-secondary">
    <div class="ul-non-padding ul-non-margin">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<!--赤文字のフラッシュメッセージ、患者側のエラーだけ別で設定。redirectに対応している。-->
<% if patient_signed_in? && value == "・症状を入力してください" %>
  <% class_name = "text-dark" %>
<% else %>
  <% class_name = "text-danger" %>
<% end %>
  <%= content_tag(:p, value, class: "alert alert-#{key} mt-2 #{class_name}") %>
<% end %>

app/views/layouts/_header_admin.html.erb
<!--歯科医院側のヘッダー-->
<nav class="navbar navbar-light px-0" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/admin/top"><%= image_tag 'dentalapo2.png', :size => '140x30' %></a>
      <div class="menu mx-2">
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
        </ul>
      </div>
      <div>
        <!--検索窓-->
        <%= form_with url: search_admin_patients_path, method: :get, local: true, class: 'form-inline my-0 input-group' do |f| %>
          <%= f.text_field :keyword, value: @keyword, placeholder: '【ID】か【カナ】で検索', required: 'required', class: 'form-control', 'aria-describedby': 'search-submit' %>
          <div class="input-group-append">
            <%= button_tag type: "submit", class: "btn btn-outline-secondary", id: 'search-submit' do %>
              <i class="fas fa-search"></i>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</nav>

app/views/layouts/_header_admin_top.html.erb
<nav class="navbar navbar-light px-0" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/admin/top"><%= image_tag 'dentalapo2.png', :size => '140x30' %></a>
      <div class="menu mx-2">
        <ul class="navbar-nav">
          <li class="nav-item">
            <!--トップページのヘッダーはログアウトリンク表示-->
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>ログアウト<i class="fas fa-sign-out-alt ml-2"></i><% end %>
          </li>
        </ul>
      </div>
      <div>
        <!--検索窓-->
        <%= form_with url: search_admin_patients_path, method: :get, local: true, class: 'form-inline my-0 input-group' do |f| %>
          <%= f.text_field :keyword, value: @keyword, placeholder: '【ID】か【カナ】で検索', required: 'required', class: 'form-control', 'aria-describedby': 'search-submit' %>
          <div class="input-group-append">
            <%= button_tag type: "submit", class: "btn btn-outline-secondary", id: 'search-submit' do %>
              <i class="fas fa-search"></i>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</nav>

app/views/layouts/_header_patient.html.erb
<nav class="navbar navbar-light px-0" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/public/top"><%= image_tag 'dentalapo2.png', :size => '140x30' %></a>
    <!--書き換え勉強用-->
    <%#= link_to root_path, class: 'navbar-brand' do %>
      <%#= image_tag 'dentalapo2.png', :size => '140x30' %>
    <%# end %>
      <div class="menu mx-2">
        <ul class="navbar-nav">
          <li class="nav-item">
            <% if current_patient.full_name.present? %>
              ようこそ、<%= current_patient.full_name %>さん！
            <% else %>
              ようこそ、<%= current_patient.full_name_kana %>さん！
            <% end %>
          </li>
        </ul>
      </div>

  </div>
</nav>

app/views/layouts/_item_sidebar.html.erb
<div class='col-md-1 sidebar-all'>
  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_employees_path do %>
          スタッフ<i class="fas fa-user-friends ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_treatments_path do %>
          治療<i class="fas fa-teeth-open ml-1"></i></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_symptoms_path do %>
          症状<i class="fas fa-teeth ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_infections_path do %>
          感染症<i class="fas fa-viruses ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_top_path do %>
          topへ<i class="fas fa-hand-point-left ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_public_sidebar.html.erb
<!--患者ログイン前とログイン後のサイドバー-->
<% if patient_signed_in? %>

<div class='col-md-1 sidebar-all'>
  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <%= link_to public_top_path(patient_id: @patient) do %>
          予約取得<i class="fas fa-tooth ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to history_public_appointment_path(current_patient) do %>
          予約履歴
          <% unchecked_count = current_patient.unchecked_appointments.count %>
          <div class="maru <%= "border-black" if unchecked_count == 0 %>">
            <%= unchecked_count %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to public_patient_path(current_patient) do %>
          登録情報<i class="fas fa-user-cog ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to destroy_patient_session_path, method: :delete do %>
          ログアウト<!--Log out<i class="fas fa-sign-out-alt ml-2"></i>-->
        <% end %>
      </div>
    </div>
  </div>
</div>

<% else %>

<div class='col-md-1 sidebar-all'>

  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <%= link_to public_top_path(patient_id: @patient) do %>
          予約状況<i class="fas fa-tooth ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <%= link_to new_patient_registration_path(patient_id: @patient) do %>
          新規登録<i class="fas fa-user-plus ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <%= link_to patient_session_path(patient_id: @patient) do %>
          ログイン<i class="fas fa-sign-in-alt ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/layouts/_sidebar.html.erb
<div class='col-md-1 sidebar-all'>
  <div class="sidebar mb-2 mb-md-3 mt-0 mt-md-3">
    <div class="row">
      <div class="col">
        <!--当日の予約一覧が表示される-->
        <%= link_to admin_appointments_path(day: Date.current.strftime('%Y-%m-%d')) do %>
          予約一覧<i class="fas fa-tooth ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to new_admin_patient_path do %>
          患者登録<i class="fas fa-user-plus ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_patients_path do %>
          患者一覧<i class="fas fa-users ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_appointment_request_index_path do %>
          承認待ち
          <div class="maru <%= "border-black" if request_count == 0 %>">
            <%= request_count %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="sidebar mb-2 mb-md-3">
    <div class="row">
      <div class="col">
        <%= link_to admin_item_path do %>
          項目編集<i class="fas fa-pencil-alt ml-1"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dental apo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <% if admin_signed_in? %>
        <%= render 'layouts/header_admin' %>
      <% elsif patient_signed_in? %>
        <%= render "layouts/header_patient" %>
      <% else %>
        <%= render 'layouts/default_header' %>
      <% end %>
    </header>
    <main>
      <div class='container-fluid'>
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/layouts/application_top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DentalAppointment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <!--アドミントップページのヘッダー変えるため（ログアウトボタン）-->
      <% if admin_signed_in? %>
        <%= render 'layouts/header_admin_top' %>
      <% else %>
        <%= render 'layouts/default_header' %>
      <% end %>
    </header>
    <main>
      <div class='container-fluid'>
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>